### DISCUSSION TITLE
How to add config when using docker-compose?

### DISCUSSION THREAD

**Discussion by Iskander495** [gogatekeeper/gatekeeper#453] [Q&A] [answered]
Hello, can you please tell me where I need to mount config.yaml so that the application will use it at startup?

  hello-world-proxy:
    container_name: hello-world-proxy
    image: quay.io/gogatekeeper/gatekeeper:2.10.0
    restart: unless-stopped
    depends_on:
      - keycloak
    volumes:
      - ./config/gogatekeeper/:/opt/gatekeeper/config.yaml
    ports:
      - 80:3000

Not worked for me :(

I get an error when starting: [error] you have not specified the listening interface 
although the parameter is specified in the config
listen: 0.0.0.0:3000

**Comment by ikhomutov** [comment, marked as answer]
Not sure if this is still relevant, but in your case, you need to specify PROXY_CONFIG_FILE environment variable and change a bit the way you mount you config file
```yaml
volumes:
- ./config/gogatekeeper/:/opt/gatekeeper/
environment:
- PROXY_CONFIG_FILE=/opt/gatekeeper/config.yaml
```
