### ISSUE TITLE
Gatekeeper requires the `iss`-claim in the auth-token

### ISSUE THREAD

**Issue by n0emis** [gogatekeeper/gatekeeper#11]
# Gatekeeper requires the `iss`-claim in the auth-token

## Summary 
Gatekeeper does not work with SimpleSamlPHP (with the OIDC-Module enabled) as a IdP. 

Gatekeeper requires the `access_token` to have specific information (for example groups, the `iss`-claim etc..). 

Following the OpenID Connect Spec, all this data should be in the `id_token` (https://openid.net/specs/openid-connect-core-1_0.html#IDToken). But since gatekeeper only uses the `access_token`, this data will not be used. Therefor gatekeeper is not fully spec-compliant.

## Environment

- OS: Linux
- Kernel (e.g. `uname -a`): 5.9.13-arch1-1
- Go (e.g. go version): go1.15.6
- Server (e.g. Keycloak or any other IdP): SimpleSamlPHP
- Louketo: 1.0.0

## Expected Results
Logging in should work

## Actual Results
```
error	louketo-proxy/handlers.go:152	unable to verify the id token	{"error": "oidc: JWT claims invalid: missing claim: 'iss'"}
info	louketo-proxy/middleware.go:146	client request	{"latency": 0.881592596, "status": 403, "bytes": 0, "client_ip": "127.0.0.1:60538", "method": "GET", "path": "/oauth/callback"}
```

## Steps to reproduce

1. Configure gatekeeper like this:
```yaml
client-id: _9e76c54497415dfbd2774738c5ca8ba4abd7ddfec6
discovery-url: https://simplesaml.n0emis.tk
encryption_key: foobar2342
secure-cookie: false
listen: :3000
redirection-url: http://127.0.0.1:3000
upstream-url: http://127.0.0.1:8000

resources:
- uri: /*
```

2. Try to log in

## Additional Information

I will leave simplesamlphp configured and this client enabled so that other people can test. (It requires no authentification, since it is configured to only returns static userinfo)
