### ISSUE TITLE
unable to alow site root only with `enable-default-deny-strict` enabled

### ISSUE THREAD

**Issue by nikolaevn** [gogatekeeper/gatekeeper#258]
# Unable to alow site root only with `enable-default-deny-strict` enabled

## Summary

I need to protect only site root (http `GET /` request), and deny any other requests.
Configuration used:

```yaml
.....
enable-default-deny: false
enable-default-deny-strict: true

resources:
- uri: /
  methods:
  - GET
  roles:
   - 'some-client:my-super-role'
```

## Expected Results
gatekeeper deny unauthorized requests `GET /` (allow authorized) and deny any other request to any locations (authorized or not).

## Actual Results

```sh
$./gatekeeper --config myconfig.yaml

[error] you need a wildcard on the url resource to cover all request i.e. --resources=uri=/*

```

## Additional Information

I think that [this check](https://github.com/gogatekeeper/gatekeeper/blob/37db2a3ea4bd8c53a39ea0fca8500ed2c3d23d1c/pkg/authorization/resource.go#L139) is not needed. I have no ideas why we need it.

**Comment by p53** [comment]
it is a little bit weird that you want to allow access only to "/", anyway i need to check what was historical reason to add this condition

**Comment by nikolaevn** [comment]
> it is a little bit weird that you want to allow access only to "/", anyway i need to check what was historical reason to add this condition

It was just a minimal example. 
Other example that also not works:

```yaml
enable-default-deny: false
enable-default-deny-strict: true

resources:
- uri: /
  methods:
  - GET
  roles:
   - 'some-client:my-super-role'

- uri: /public
  methods:
  - GET
  white-listed: true
```
