### ISSUE TITLE
Support of Redis database

### ISSUE THREAD

**Issue by eratolekov** [gogatekeeper/gatekeeper#357]
# Gogatekeeper does not support selecting of a redis database

## Summary

Gogatekeeper always connects to /0 redis database. Even though the database name is setted explicitly, e.g. /14.

## Environment
Gogatekeeper 2.8.0 (official docker image)

The gogatekeeper helm values:
```yaml
config:
  listen: :8080
  listen-admin: :8090
  ...
  no-redirects: false
  store-url: redis://redis-headless.redis-dev.svc.cluster.local:6379/14
  forbidden-page: custom-error.html
  ...
```

Redis docker image:
docker.io/bitnami/redis:7.0.7-debian-11-r7

## Expected Results

The encrypted tokens are stored in /14 redis database.

```bash
redis-cli
127.0.0.1:6379> select 14
OK
127.0.0.1:6379[14]> keys *
"<some-key>"
```

## Actual Results

The encrypted tokens are stored in /0 redis database.

```bash
127.0.0.1:6379> select 14
OK
127.0.0.1:6379[14]> keys *
(empty array)
127.0.0.1:6379[14]> select 0
OK
127.0.0.1:6379> keys *
1) "<some-key>"
```

## Steps to reproduce

1. Deploy the gogatekeeper
2. Open the url of protected resource with browser
3. Log in
4. Check the redis with `redis-cli`
