### ISSUE TITLE
Struggling from CORS issues (documentation small issue)

### ISSUE THREAD

**Issue by hillout** [gogatekeeper/gatekeeper#384]
Hi! 

All divide the issue into two parts. First on our problem we're trying to solve, second one - typo in the docs. 

1. We've got a web app (a separate front-end and back-end). 
Front-end is written in VUE JS 2.0, has address - http://localhost:8081
Back-end - written on php - http://localhost:8080

On front-end we've implemented Keycloak adapter, so once we reach localhost:8081 it redirects us to KC server, and after authentication redirects us back to the front. Front puts the kc-access token to "Authorization Bearer {token}" header within each interaction with back-end through **gatekeeper** (http://localhost:20000) with "no-redirect=true" flag. But this scheme does not work, web console logs are saying: 

```
Access to XMLHttpRequest at 'http://localhost:20000/web/static-data' from origin 'http://localhost:8081' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Gatekeeper logs:**
```
[cors] 2023/11/22 16:58:34   Handler: Preflight request
[cors] 2023/11/22 16:58:34   Preflight aborted: origin 'http://localhost:8081' not allowed
2023-11-22T16:58:34.626+0300 info proxy/middleware.go:138 client request  {"headers": {"Accept":["*/*"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"],
"Access-Control-Request-Headers":["authorization,cache-control"],"Access-Control-Request-Method":["POST"],"Connection":["keep-alive"],
"Origin":["http://localhost:8081"],"Referer":["http://localhost:8081/"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-site"],
"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"]}, 
"path": "/web/static-data", "method": "OPTIONS", "latency": 0.000969551, "status": 204, "bytes": 0, 
"client_ip": "172.21.193.65", "remote_addr": "172.21.193.65:52580", "method": "OPTIONS", "path": "/web/static-data"}
```
Especially this fragment is a bit suspicious: `Preflight aborted: origin http://localhost:8081' not allowed`

**Gatekeeper config**:
```
gatekeeper-1:
    container_name: gatekeeper-app-1
    image: quay.io/gogatekeeper/gatekeeper:2.9.0
    command:
#      - "--config=/config.yml"
      - "--enable-logging=true" ## http requests logging
      - "--verbose=true"
      - "--enable-json-logging=false"
      - "--client-id=${app1_id}"
      - "--client-secret=${app1_secret}"
      - "--discovery-url=http://localhost:9999/realms/SSO-test/.well-known/openid-configuration"
      - "--listen=:20000"
      - "--upstream-url=http://localhost:8080"
      - "--cors-origins=*"
      - "--cors-methods=GET,POST,OPTIONS,HEAD,DELETE"
      - "--cors-headers=authorization,content-type"
      - "--cors-exposed-headers=*"
      - "--cors-credentials=true"
      - "--cors-max-age=72000s"
      - "--skip-access-token-clientid-check=true"
      - "--skip-access-token-issuer-check=true"
      - "--enable-authorization-header=true"
      - "--no-redirects=true"
      - "--scopes=openid"
    ports:
      - 20000:20000
    volumes:
#      - ./config.yml:/config.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
```
All containers are in the same docker network. We've tried two approaches in configurations - by commands, and by config.yml file. Did not help. If we remove GK container and ask front to interact to back directly - no CORS issues. The Back-end has predefined cors setting in order to allow requests from domains: http://localhost:8081, http://localhost:20000 and so on, we've even tried '*' just in case.  

2. And there is a small issue in documentation, which confused us. 
If you open up userguide (https://gogatekeeper.github.io/gatekeeper/userguide/) - find --cors-expose**s**-headers, whereas on  https://gogatekeeper.github.io/gatekeeper/configuration/ page it sound slightly different: "–cors-expos**ed**-headers value". Please advise.
It would have been be more informative if there were more detailed examples with CORS related flags.

Maybe you can give us a hint how can we resolve it ? 

Thanks for you attention!
