### ISSUE TITLE
Forward-auth traefik with gatekeeper

### ISSUE THREAD

**Issue by hillout** [gogatekeeper/gatekeeper#390]
Hi! 

Can't quite understand how forward-auth configs should be made:

Following by the manual `traefik forward-auth configuration when you WANT to redirect user to authentication server by gatekeeper (useful for e.g. frontend application authentication).` 

I'm having the gatekeeper deployed with: 

```
  gatekeeper:
    container_name: gatekeeper-proxy
    image: quay.io/gogatekeeper/gatekeeper:2.8.0
    command:
      - --client-id=client_id  
      - --no-redirects=false # this option will ensure there WILL BE redirects to keycloak server
      - --no-proxy=true # this option will ensure that request will be not forwarded to upstream
      - --listen=0.0.0.0:4180
      - --discovery-url=https://keycloak.domain.org/realms/network/.well-known/openid-configuration
      - --enable-default-deny=true 
    restart: always
    networks:
      - net
```

By the way, why there is no client-secret here? (although I tried with it as well).

Traefik dynamic config:

```
http:
  routers:
    app:
      entryPoints:
        - "websecure"
      rule: "Host(`domain.org`)"
      middlewares:
        - "app-middleware"
        - "app-headers"
      tls:
        certResolver: letsencrypt
      service: app-service
      
        
  middlewares:
    app-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
          X-Forwarded-Host: domain.org
          X-Forwarded-Uri: /

    app-middleware:
      forwardAuth:
        address: "http://192.168.140.93:4180" # gatekeeper container
        trustForwardHeader: true
        authResponseHeaders:
          - Set-Cookie
        authRequestHeaders:
          - "Accept"
          - "Authorization"
          - "Cookie"
          
  services:          
    app-service:
      loadBalancer:
        servers:
          - url: "http://192.168.x.x:80"
        passHostHeader: true
```

And I'm getting the infinite redirect: 

![Screenshot from 2023-12-01 10-50-46](https://github.com/gogatekeeper/gatekeeper/assets/15137897/5d36be3a-4a41-4431-963c-846cb4b0a641)

And Gatekeeper logs: 
```
error	no session found in request, redirecting for authorization	{"error": "authentication session not found"}
```

Judging by the docs I have to put some:
      `- --resources=headers=x-some-header:somevalue,x-other-header:othervalue`
No idea, what should I put there.

**Comment by p53** [comment]
@hillout did you look at manifest link, also on this line https://github.com/gogatekeeper/gatekeeper/blob/d1a210f33cad4e1fa407d2431f9ad7fb7471e786/e2e/k8s/manifest_test_forwardauth.yml#L2551 ?

**Comment by p53** [comment]
also please use enable-encrypted-token, idp session check option when possible

**Comment by hillout** [comment]
@p53 haven't got any experience with k8s yet. 


> also please use enable-encrypted-token, idp session check option when possible

I am, but since it wasn't working for me I started thinking that  I should stick to docs, cuz in the docs there aren't specified fields for that.

Following the manifest I can't understand how the routes should be configured in the dynamic traefik config. How to interprotate this:

```
      - path: /oauth
        pathType: Prefix
        backend:
          service:
            name: gate
            port:
              number: 8081
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8081
```

Should I add additional routes to `/` and `/oauth` accordingly ? And if I do this for my domain there is gonna be no sense if I route `/` to keycloak..

**Comment by p53** [comment]
setup only that route /oauth to gatekeeper, that route should not be authenticated, because there are gatekeeper handlers

**Comment by hillout** [comment]
Tried like this where specified `http://192.168.140.93:4180/oauth`, didnt' work:
Must be missing something. 

```
http:
  routers:
    app:
      entryPoints:
        - "websecure"
      rule: "Host(`domain.org`)"
      middlewares:
        - "app-middleware"
        - "app-headers"
      tls:
        certResolver: letsencrypt
      service: app-service
      
        
  middlewares:
    app-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
          X-Forwarded-Host: domain.org
          X-Forwarded-Uri: /

    app-middleware:
      forwardAuth:
        address: "http://192.168.140.93:4180/oauth" # gatekeeper container address
        trustForwardHeader: true
        authResponseHeaders:
          - Set-Cookie
        authRequestHeaders:
          - "Accept"
          - "Authorization"
          - "Cookie"
          
  services:          
    app-service:
      loadBalancer:
        servers:
          - url: "http://192.168.x.x:80" # App container address
        passHostHeader: true
```

**Comment by p53** [comment]
@hillout you should not give it after gatekeeper url to forwardAuth section, you should forward all paths with prefix /oauth to gatekeeper from traefik docs:

```
## Dynamic configuration
http:
  routers:
    my-router:
      rule: "Path(`/foo`)"
      service: service-foo
```

**Comment by hillout** [comment]
@p53 hi, 

Sorry for the delay, seems it's working.
I changed my dynamic config in traefik config:

 ```
http:
  routers:
    app:
      entryPoints:
        - "websecure"
      rule: "Host(`domain.org`)"
      middlewares:
        - "app-middleware"
        - "app-headers"
      tls:
        certResolver: letsencrypt
      service: app-service

    app-proxy:
      entryPoints:
        - "websecure"
      rule: "Host(`domain.org`) && PathPrefix(`/oauth`)"
      tls:
        certResolver: letsencrypt
      service: app-proxy
 
################     
  
   middlewares:
     app-headers:
       headers:
         customRequestHeaders:
           X-Forwarded-Proto: https
           X-Forwarded-Host: domain.org
           X-Forwarded-Uri: /

     app-middleware:
       forwardAuth:
         address: "http://192.168.140.93:4180 # gatekeeper container address

#####################          
  services:          
    app-**service**:
      loadBalancer:
        servers:
          - url: "http://192.168.x.x:80" # App container address
        passHostHeader: true

    app-**proxy**:
      loadBalancer:
        servers:
          - url: "http://192.168.x.x:4180" # Gatekeeper container address
        passHostHeader: true
```

So, after going to domain.org I'm getting redirected to KC and back again to my app. Logs in gk show me: 

```
info	issuing access token for user	{"email": "user@mail.org", "sub": "6c85c796-d274-4b0b-bcd1-dcf2ee1881ea", "expires": "2023-12-05T21:39:42Z", "duration": "4m59.599171659s"}

```
