### ISSUE TITLE
Gatekeeper security with -no-redirects=true

### ISSUE THREAD

**Issue by hillout** [gogatekeeper/gatekeeper#411]
Hi! 

Recentrly we've switched over from GK for front to native Keycloak JS adapter, which is quite simple to develop and deploy, but we didn't take out GK which is a guard for our backend (written on php). 

Here is a small diagram:

![Screenshot from 2024-01-31 17-06-31](https://github.com/gogatekeeper/gatekeeper/assets/15137897/afc7dec4-0384-4d8a-9eef-c7f6ac808fa3)

And again I split my questions into two parts.

1. I've noticed that there is no need to create a client inside the Keycloak if I set GK for guarding backend with the following config: 

```yaml
  gatekeeper-1:
    container_name: gatekeeper-backend-app-1
    image: ${DOCKER_REGISTRY_MIRROR}gatekeeper:${GK_VERSION}
    command:
      - "--enable-logging=true"
      - "--verbose=false"
      - "--enable-json-logging=false"
      - "--client-id=${app1_id}"
      - "--discovery-url=http://localhost:${KC_PORT}/realms/SSO-test/.well-known/openid-configuration"
      - "--listen=:20000"
      - "--upstream-url=http://localhost:${app1_backend_port}"
      - "--enable-default-deny=true"
      - "--enable-authorization-header=true"
      - "--no-redirects=true"
      - "--skip-access-token-clientid-check=true"
      - "--skip-access-token-issuer-check=true"
      - "--enable-idp-session-check=false"
      - "--resources=uri=/web/version*|white-listed=true"
      - "--upstream-timeout=3600s"
      - "--upstream-response-header-timeout=3600s"
      - "--upstream-expect-continue-timeout=3600s"
      - "--server-read-timeout=3600s"
      - "--server-write-timeout=3600s"
    ports:
      - ${gk1_port}:20000      
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - net
    depends_on:
      keycloak:
        condition: service_healthy
    extra_hosts:
      - "localhost:${LOCAL_IP}"
```

But for Gatekeeper it's crucial to have client-id parameter, otherwise it won't start. Maybe GK should contain the client-id if only it suppose to work by Authorization Code flow and/or + PKCE ? The main flag responsible for starting this flow is - `"--no-redirects=true"`, so, if it's `false`, maybe there is no need for client-id ?

2. The second part concerns the recent message:

SECURITY NOTICE:
Unaffected - if you use one of these options, you are not susceptible to this attack:
--enable-encrypted-token=true
--store-url=<redis-url>
--enable-idp-session-check=true

We're passing the token from frontend to backend for retrieving users' roles from /userinfo. Just want to be sure that in this case the notice is not touching this case, and also get to know whether it has any sense to have `- "--enable-idp-session-check=true"` ?
