### ISSUE TITLE
Failed to pass resources args - invalid identifier

### ISSUE THREAD

**Issue by NonneTrapuE** [gogatekeeper/gatekeeper#474]
Hi ! 

I encounter a problem with optionals args resources. I can't use "white-listed", i have an error :

> [error] invalid resource 'uri=/#/s/*|white-listed=true', invalid identifier, should be roles, uri or methods

My Yaml file : 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogatekeeper
  annotations:
    meta.helm.sh/release-namespace: yopass
  namespace: yopass
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gogatekeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gogatekeeper
    spec:
      containers:
        - name: gogatekeeper
          image: quay.io/gogatekeeper/gatekeeper:2.12.0
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          args:
            - "--config=/config/gogatekeeper.yaml"
            - "--resources='uri=/#/s/*|white-listed=true'"
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
          - name: gogatekeeper-yaml
            mountPath: "/config"
            readOnly: True
      dnsPolicy: ClusterFirst
      volumes:
      - name: gogatekeeper-yaml
        configMap:
          name: gogatekeeper-yaml
          items:
            - key: "gogatekeeper.yaml"
              path: "gogatekeeper.yaml"
```
While in doc, you can use this resources args.

Any idea ?

Thanks !
