### ISSUE TITLE
Ability to define NoRedirect=true per URL path

### ISSUE THREAD

**Issue by p53** [gogatekeeper/gatekeeper#541]
# Title
Ability to define NoRedirect=true per URL path, requested by user in https://github.com/gogatekeeper/gatekeeper/pull/532

## Summary 

Right now there is NoRedirect option, which is global and defines if gatekeeper uses AuthorizationCode flow for getting token or API Bearer token to authenticate incoming request. Problem is that if you want to use both e.g. AuthorizationCode flow for some part of your endpoints and API flow for different set of endpoints you have to use two gatekeepers. 

## Why?

With this feature user will be able to define no-redirect=true per resource, so user will be able to use one gatekeeper to protect both e.g. user facing pages and api endpoints

## How

we will add new option in resources, no-redirect, which is only considered when no-redirect=true

## Acceptance criteria

backward compatibility, ability to make no-redirect=true per path

**Comment by p53** [comment]
@jackhg96 @colla @stemyers @oyelekci @aryakumargeorge @hitesh-ladha could you try 3.1.0-rc1 release, there is also docker image

Quick docu, you can set no-redirect=true per resource:
```
no-redirects: false
resources:
- uri: /admin/test
  # the methods on this URL that should be protected, uri is required when defining resource
  method: GET
  no-redirect: true
```

IMPORTANT!!: the other way it doesn't work (because of technical reasons to keep backward compatibility):
```
# this won't work
no-redirects: true
resources:
- uri: /admin/test
  # the methods on this URL that should be protected, uri is required when defining resource
  method: GET
  no-redirect: false
```
